### ISSUE TITLE
[LoadError] cannot load such file -- irb/slex

### ISSUE THREAD

**Issue by Shankar1598** [castwide/vscode-solargraph#137]
solargraph version: 0.20.0
ruby version: 2.6.3p62
OS: Manjaro Arch
VSCode: 1.36.1
StackTrace:
```
Solargraph is listening on stdio PID=18656
[WARN] Error processing request: [LoadError] cannot load such file -- irb/slex
[WARN] /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/parser/ruby/legacy/ruby_lex.rb:2:in `<top (required)>'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/parser/ruby/legacy/token_list.rb:5:in `<class:TokenList>'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/parser/ruby/legacy/token_list.rb:4:in `<module:Legacy>'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/parser/ruby/legacy/token_list.rb:3:in `<module:YARD>'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/parser/ruby/legacy/token_list.rb:2:in `<top (required)>'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/tags/overload_tag.rb:59:in `parse_signature'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/tags/overload_tag.rb:10:in `initialize'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/tags/library.rb:162:in `new'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/tags/library.rb:162:in `overload_tag'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/tags/library.rb:274:in `tag_create'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/docstring_parser.rb:215:in `create_tag'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/docstring_parser.rb:156:in `block in parse_content'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/docstring_parser.rb:142:in `each'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/docstring_parser.rb:142:in `each_with_index'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/docstring_parser.rb:142:in `parse_content'
/home/user/.gem/ruby/2.6.0/gems/yard-0.9.20/lib/yard/docstring_parser.rb:117:in `parse'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/source.rb:539:in `parse_docstring'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/pin/reference/override.rb:22:in `from_comment'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/core_fills.rb:26:in `<module:CoreFills>'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/core_fills.rb:4:in `<module:Solargraph>'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/core_fills.rb:3:in `<top (required)>'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/yard_map.rb:102:in `core_pins'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/yard_map.rb:203:in `process_requires'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/yard_map.rb:45:in `initialize'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/api_map.rb:38:in `new'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/api_map.rb:38:in `block in index'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/api_map.rb:35:in `synchronize'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/api_map.rb:35:in `index'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/api_map.rb:29:in `initialize'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/library.rb:389:in `new'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/library.rb:389:in `api_map'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/library.rb:23:in `initialize'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/library.rb:363:in `new'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/library.rb:363:in `load'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/host.rb:269:in `prepare'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/host.rb:286:in `block in prepare_folders'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/host.rb:285:in `each'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/host.rb:285:in `prepare_folders'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/message/initialize.rb:14:in `block in process'
/usr/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/message/initialize.rb:10:in `process'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/host.rb:101:in `receive'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/adapter.rb:47:in `process'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/data_reader.rb:55:in `parse_message_from_buffer'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/data_reader.rb:33:in `block in receive'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/data_reader.rb:28:in `each_char'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/data_reader.rb:28:in `receive'
/home/user/.gem/ruby/2.6.0/gems/solargraph-0.35.0/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
/home/user/.gem/ruby/2.6.0/gems/backport-1.1.1/lib/backport/client.rb:63:in `tick'
/home/user/.gem/ruby/2.6.0/gems/backport-1.1.1/lib/backport/server/stdio.rb:18:in `update'
/usr/lib/ruby/2.6.0/observer.rb:197:in `block in notify_observers'
/usr/lib/ruby/2.6.0/observer.rb:196:in `each'
/usr/lib/ruby/2.6.0/observer.rb:196:in `notify_observers'
/home/user/.gem/ruby/2.6.0/gems/backport-1.1.1/lib/backport/client.rb:121:in `read_input'
/home/user/.gem/ruby/2.6.0/gems/backport-1.1.1/lib/backport/client.rb:102:in `block in run_input_thread'
[Error - 12:15:16 pm] Server initialization failed.
  Message: [LoadError] cannot load such file -- irb/slex
  Code: -32603 
```

**Comment by Shankar1598** [comment]
Any ideas?

**Comment by castwide** [comment]
I'm not sure. Solargraph doesn't require irb/slex, so I suspect the problem is originating somewhere else.

Possibly related: https://stackoverflow.com/questions/2904594/problems-installing-rdoc-irb-bluecloth-chronic-on-fedora-12

**Comment by Shankar1598** [comment]
The issue got fixed after I installed `ruby-irb` package.
