### ISSUE TITLE
Failled to start solargraph: TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by ricsdeol** [castwide/vscode-solargraph#146]
VS Code Info:

> Version: 1.38.1
> OS: Linux installed by Snap (stable:    b37e54c9 2019-09-18 (15) 143MB classic)

Ruby: 2.6.3
SolarGraph plugin: 0.21.1 - August 11, 2019
Solargraph version: 0.37.2

Log:

``` 
[Error - 2:02:16 PM] Starting client failed
TypeError: Cannot read property 'on' of undefined
    at Promise (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/out/src/language-client.js:80:34)
    at new Promise (<anonymous>)
    at selectClient (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/out/src/language-client.js:78:24)
    at LanguageClient.createMessageTransports (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/node_modules/vscode-languageclient/lib/main.js:176:20)
    at LanguageClient.createConnection (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/node_modules/vscode-languageclient/lib/client.js:2025:21)
    at LanguageClient.resolveConnection (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/node_modules/vscode-languageclient/lib/client.js:1839:44)
    at LanguageClient.start (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/node_modules/vscode-languageclient/lib/client.js:1770:14)
    at startLanguageServer (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/out/src/extension.js:46:43)
    at activate (/home/ricsdeol/.vscode/extensions/castwide.solargraph-0.21.1/out/src/extension.js:152:5)
    at Function._callActivateOptional (/snap/code/15/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:656:440)
    at Function._callActivate (/snap/code/15/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:656:91)
    at A._doActivateExtension.Promise.all.then.i (/snap/code/15/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:655:131)
```

Could you please help me?

**Comment by castwide** [comment]
It looks like the extension is unable to run the `solargraph` executable.

If you run `solargraph -v` from VS Code's integrated terminal, do you get an error?

**Comment by ricsdeol** [comment]
> If you run `solargraph -v` from VS Code's integrated terminal, do you get an error?

No, it's ok:
```
╭─ricsdeol at ricsdeol-G3-3579 in ~/projects/indeva/product/web on ft/gem_updates✘✘✘  using 2.5.1 19-10-01-14:54:40
╰─○ solargraph -v
0.37.2
```

**Comment by castwide** [comment]
`solargraph.bundlerPath` and `solargraph.commandPath` need to include the filename, e.g., `/path/to/bundler` and `/path/to/solargraph`.
