### ISSUE TITLE
"Solargraph gem not found.." error persists in Flatpak

### ISSUE THREAD

**Issue by Ashvith** [castwide/vscode-solargraph#241]
I am assuming that it is probably because of the sand boxing, but I am not able to resolve this. I get this in the OUTPUT tab:
```sh
[Error - 1:54:34 am] Starting client failed
Error: spawn solargraph ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by johan-smits** [comment]
Did you solve it?
