### ISSUE TITLE
Fails to start in VSCode: "[Errno::EBADF] Bad file descriptor - ruby"

### ISSUE THREAD

**Issue by gbirchmeier** [castwide/vscode-solargraph#245]
* solargraph gem 0.44.3
* Ruby Solargraph plugin 0.23.0
* VSCode 1.66.0
* Ubuntu 20.4
* ruby: jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 17.0.2+8 on 17.0.2+8 +jit [linux-x86_64]

I have done the following
* installed plugin
* added gem to Gemfile and run `bundle install`
* checked the box for "Use `bundle exec` to run solargraph"

When VSCode starts, Solargraph fails with this:

![image](https://user-images.githubusercontent.com/237288/162030734-49c73d13-c859-41c7-bc41-d4359ae9c34c.png)

The only error log I can find is in the OUTPUT tab -> "Log (Window)":
```
[2022-04-06 11:58:21.423] [renderer1] [error] [Errno::EBADF] Bad file descriptor - ruby: Error: [Errno::EBADF] Bad file descriptor - ruby
    at handleResponse (/home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (node:internal/timers:464:21)
[2022-04-06 11:58:21.436] [renderer1] [error] write after end: Error: write after end
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:319:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:90:29
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)
    at StreamMessageWriter.doWrite (/home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)
    at /home/grant.birchmeier/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29
```

... but I don't really know what this means or what command is being used to get this result.

I ran `bundle exec solargraph scan`, but didn't see any red flags.

I tried it with a brand-new config created from `bundle exec solargraph config` to make sure that wasn't the issue.  Same result.

**Comment by gbirchmeier** [comment]
Closing this.  I believe my error has something to do with how we have installed Ruby via the asdf tool.
