### ISSUE TITLE
Solargraph for VSCode doesn't work anymore

### ISSUE THREAD

**Issue by mtrepanier** [castwide/vscode-solargraph#277]
Hello all, 

I have an issue where Solargraph Ruby for VSCode stopped working after a Mac Update to Sonoma 14.7

Everything was working fine before.  

What I did so far:

- Reinstall VS Code (differents version)
- Reinstall the extension (differents versions here too)
- Uninstalled all other extensions (Only have one for Packwerk)
- Resinstall the Solargraph gem
```
solargraph -v
0.50.0
```

Here's the error I get in the VSCode Console, when I hover something in the code
```
[Error - 4:44:51 PM] Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
  Code: -32603 
[Error - 4:44:52 PM] Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
  Code: -32603 
[Error - 4:44:53 PM] Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
  Code: -32603 
```
And here the Dev tool console log
```
console.ts:137 [Extension Host] [WARN] Error processing request: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
[WARN] /Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:2121:in `method_missing'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/dependency.rb:293:in `to_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1020:in `map'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1020:in `unresolved_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:998:in `find_in_unresolved'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:92:in `block in require'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `synchronize'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/api_map.rb:3:in `<top (required)>'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:500:in `api_map'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:385:in `catalog_inlock'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:59:in `block in attach'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:50:in `synchronize'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:50:in `attach'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:63:in `block in explicit_library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:61:in `each'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:61:in `explicit_library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:41:in `library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:532:in `definitions_at'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/message/text_document/hover.rb:12:in `process'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:112:in `receive'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:53:in `tick'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:44:in `block in start'

console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
	at handleResponse (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:483:21)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [castwide.solargraph][NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
	at handleResponse (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:483:21)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] [WARN] Error processing request: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification

console.ts:137 [Extension Host] [WARN] /Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:2121:in `method_missing'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/dependency.rb:293:in `to_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1020:in `map'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1020:in `unresolved_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:998:in `find_in_unresolved'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:92:in `block in require'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `synchronize'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/api_map.rb:3:in `<top (required)>'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:500:in `api_map'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:385:in `catalog_inlock'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:59:in `block in attach'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:50:in `synchronize'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:50:in `attach'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:63:in `block in explicit_library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:61:in `each'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:61:in `explicit_library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:41:in `library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:532:in `definitions_at'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/message/text_document/hover.rb:12:in `process'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:112:in `receive'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:53:in `tick'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:44:in `block in start'

console.ts:137 [Extension Host] [WARN] Error processing request: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
[WARN] /Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:2121:in `method_missing'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `reject'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/bundler-2.5.22/lib/bundler/rubygems_ext.rb:273:in `matching_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/dependency.rb:293:in `to_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1020:in `map'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:1020:in `unresolved_specs'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/specification.rb:998:in `find_in_unresolved'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:92:in `block in require'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `synchronize'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/api_map.rb:3:in `<top (required)>'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:500:in `api_map'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:385:in `catalog_inlock'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:59:in `block in attach'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:50:in `synchronize'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:50:in `attach'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:63:in `block in explicit_library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:61:in `each'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:61:in `explicit_library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/dispatch.rb:41:in `library_for'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:532:in `definitions_at'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/message/text_document/hover.rb:12:in `process'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host.rb:112:in `receive'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:53:in `tick'
/Users/some.user/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/solargraph-0.50.0/lib/solargraph/language_server/host/message_worker.rb:44:in `block in start'

console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
	at handleResponse (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:483:21)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [castwide.solargraph][NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
	at handleResponse (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:483:21)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] stack trace: Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
	at handleResponse (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:483:21)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:78 [castwide.solargraph][NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
mainThreadExtensionService.ts:79 Error: [NoMethodError] undefined method `ignored?' for an instance of Gem::Specification
	at handleResponse (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
	at processMessageQueue (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
	at Immediate.<anonymous> (/Users/some.user/.vscode/extensions/castwide.solargraph-0.24.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
	at process.processImmediate (node:internal/timers:483:21)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
```

Anyone has any clue?

**Comment by castwide** [comment]
This appears to be related to a change in the `rubygems` internals instead of something in Solargraph itself. I'm not sure of the root cause, but Solargraph gem v.0.51.0 includes some updates to dependencies and the gem mapping process that might have resolved this issue as a side effect.
