### ISSUE TITLE
Failed to start Solargraph

### ISSUE THREAD

**Issue by jesalg** [castwide/vscode-solargraph#69]
I'm on Ubuntu 14 and Ruby 2.3.3. When I call `solargraph` from the command line, I get an error:

```
$ solargraph
/home/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0xf80bd8 solargraph-0.22.0> (NoMethodError)
	from /home/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /home/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /home/myuser/.rvm/gems/ruby-2.3.3/gems/solargraph-0.22.0/lib/solargraph.rb:1:in `<top (required)>'
	from /home/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /home/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /home/myuser/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/myuser/.rvm/gems/ruby-2.3.3/gems/solargraph-0.22.0/bin/solargraph:3:in `<top (required)>'
	from /home/myuser/.rvm/gems/ruby-2.3.3/bin/solargraph:22:in `load'
	from /home/myuser/.rvm/gems/ruby-2.3.3/bin/solargraph:22:in `<main>'
	from /home/myuser/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/myuser/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas what I'm doing wrong?

**Comment by castwide** [comment]
I'm not sure what the problem is, but it looks like the error is coming from Gem::Specification. Can you try updating rubygems via `gem update --system`?

**Comment by jesalg** [comment]
@castwide That did it, thanks!!

**Comment by dominic-davies** [comment]
Thanks, I had to run gem install solargraph as well but updating my gems did no harm at all.

**Comment by 9ntonio** [comment]
`gem update --system` was the answer for me. Thank you 🙏  @castwide
